#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: hack/update_apps.sh [OPTIONS]

Options:
  --branch BRANCH   Git branch in cozystack/cozystack (default: main)
  --apps  LIST      Space- or comma-separated list of apps to update
  --dest  PATH      Destination directory to write the *.md files to
  --pkgdir DIR      Subdirectory under packages/ to fetch from (default: apps). Examples: apps, extra
  --index           Write each app into path/<app>/_index.md instead of path/<app>.md (creates subdirectory)
  -h, --help        Show this help and exit

Notes:
  * Template markdown files are expected in DEST_DIR/_include (derived automatically).
  * Each template file should be named <app>.md.

Examples:
  hack/update_apps.sh --apps "tenant redis" --dest content/en/docs/reference/applications
  hack/update_apps.sh --apps "tenant,redis" --dest content/en/docs/reference/applications --branch feature/foo
EOF
}

BRANCH="main"
DEST_DIR=""
APPS=()
INDEX_MODE="false"
PKG_DIR="apps"

# -------------------- Parse arguments --------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --branch)
      BRANCH="$2"; shift 2 ;;
    --apps)
      IFS=', ' read -r -a APPS <<< "$2"; shift 2 ;;
    --dest)
      DEST_DIR="$2"; shift 2 ;;
    --pkgdir)
      PKG_DIR="$2"; shift 2 ;;
    --index)
      INDEX_MODE="true"; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      # allow trailing positional apps as well
      if [[ "$1" == --* ]]; then
        echo "Unknown option: $1" >&2
        usage; exit 1
      else
        APPS+=("$1"); shift
      fi
      ;;
  esac
done

if [[ ${#APPS[@]} -eq 0 ]]; then
  echo "Error: no apps specified. Use --apps." >&2
  usage; exit 1
fi

if [[ -z "$DEST_DIR" ]]; then
  echo "Error: --dest is required." >&2
  usage; exit 1
fi

# Derive templates location: DEST_DIR/_include
SRC_DIR="${DEST_DIR%/}/_include"

DOCS_REPO="cozystack/website"
SOURCE_REPO="cozystack/cozystack"
RAW_BASE_URL="https://raw.githubusercontent.com/${SOURCE_REPO}/${BRANCH}/packages/${PKG_DIR}"


for app in "${APPS[@]}"; do
  if [[ "$INDEX_MODE" == "true" ]]; then
    src_file="${DEST_DIR%/}/${app}/_include/_index.md"
    dest_file="${DEST_DIR%/}/${app}/_index.md"
  else
    src_file="${DEST_DIR%/}/_include/${app}.md"
    dest_file="${DEST_DIR%/}/${app}.md"
  fi

  # Ensure template exists (touch if missing)
  [[ -f "$src_file" ]] || touch "$src_file"

  # Copy template to destination (overwrite)
  cp "$src_file" "$dest_file"

  # Insert autogenerated notice with links
  rel_template_path="${src_file#./}"
  cat >> "$dest_file" <<EOF
<!--
Autogenerated content. Don't edit this file directly; edit sources instead.
metadata: https://github.com/${DOCS_REPO}/blob/main/${rel_template_path}
source: https://github.com/${SOURCE_REPO}/blob/${BRANCH}/packages/${PKG_DIR}/${app}/README.md
-->

EOF

  readme_url="${RAW_BASE_URL}/${app}/README.md"
  echo "Processing $app..."

  if curl -fsSL "$readme_url" \
    | awk 'NR==1 && /^#{1,2} / { next } { print }' >> "$dest_file"; then
    echo "✓ Appended README for $app -> $dest_file"
  else
    echo "⚠️  Failed to fetch README for $app" >&2
  fi

done